import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from '../frontend/context/GlobalState'; // Adjust the path as necessary
import { CartProvider } from '../frontend/context/CartContext'; // Import CartProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider>
          <CartProvider> {/* Wrap children with CartProvider */}
            {children}
          </CartProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
